### ISSUE TITLE
Show fake data on the map

### ISSUE THREAD

**Issue by PromZona-Student** [PromZona-Student/Hive-Geocaching#8]
If there is still no data from customer, then need to fake minumum required data for this.
If there is data, then use it.
No need fancy icons or anything else here. Just any point, mark on the map, that we decided to place there

**Comment by kemm0** [comment]
https://github.com/users/PromZona-Student/projects/1/views/1?pane=issue&itemId=18707893 Needs to be done first

**Comment by kemm0** [comment]
Data should be fetched from mock backend's geocaches endpoint and displayed on the map
